connection:
  client: FH-Bielefeld
  serverURI: https://nbl.fh-bielefeld.de/login.php?target=&amp;soap_pw=&amp;ext_uid=&amp;cookies=nocookies&amp;client_id=FH-Bielefeld&amp;lang=de
  user: 
  userId: 
  wsdl: https://nbl.fh-bielefeld.de/webservice/soap/server.php?wsdl
courses:

localDir:
  path: 
  structureTemplate: '%. Semester ($)'
  useOwnNames: true
  useOwnStructure: true
  useYear: true
sync:
  ignoredFiles: 
  overwrite: false
  owIgnore: false
  showNew: false
  showOnly: false
  syncAll: true
  syncNotification: false
system:
  lang: en
  theme: dark
  trayicon: false
  updateCheck: false
